import type { BuildingType, EntityDef, EntityType, RaceDef, RaceId, UnitType } from './types'

export const ENTITY_DEFS: Record<UnitType | BuildingType, EntityDef> = {
  worker: {
    type: 'worker',
    kind: 'unit',
    label: 'Grave Serf',
    description: 'Harvests cursed iron and raises field structures. Fragile, but steadier near wards.',
    cost: 45,
    buildTime: 6,
    hp: 42,
    radius: 13,
    speed: 96,
    range: 26,
    damage: 3,
    attackCooldown: 1.1,
    sight: 190,
    armor: 'laborer',
    bonusAgainst: [],
    bonusDamage: 0,
    terror: 0,
    ward: 4,
    supplyCost: 1,
    supplyProvided: 0,
  },
  vanguard: {
    type: 'vanguard',
    kind: 'unit',
    label: 'Oathbound',
    description: 'Armored line infantry. Reliable under pressure and best used as the army anchor.',
    cost: 70,
    buildTime: 8,
    hp: 78,
    radius: 15,
    speed: 88,
    range: 28,
    damage: 11,
    attackCooldown: 0.95,
    sight: 230,
    armor: 'armored',
    bonusAgainst: ['structure'],
    bonusDamage: 4,
    terror: 4,
    ward: 8,
    supplyCost: 2,
    supplyProvided: 0,
  },
  skirmisher: {
    type: 'skirmisher',
    kind: 'unit',
    label: 'Ashen Arbalest',
    description: 'Fast ranged hunter. Strong at kiting, weaker when dread closes in.',
    cost: 95,
    buildTime: 10,
    hp: 58,
    radius: 14,
    speed: 120,
    range: 142,
    damage: 8,
    attackCooldown: 0.72,
    sight: 260,
    armor: 'light',
    bonusAgainst: ['armored'],
    bonusDamage: 6,
    terror: 5,
    ward: 3,
    supplyCost: 2,
    supplyProvided: 0,
  },
  command: {
    type: 'command',
    kind: 'building',
    label: 'Candle Keep',
    description: 'Primary stronghold. Trains Grave Serfs and projects a large ward against dread.',
    cost: 0,
    buildTime: 0,
    hp: 720,
    radius: 46,
    speed: 0,
    range: 0,
    damage: 0,
    attackCooldown: 0,
    sight: 320,
    armor: 'structure',
    bonusAgainst: [],
    bonusDamage: 0,
    terror: 12,
    ward: 40,
    supplyCost: 0,
    supplyProvided: 14,
  },
  barracks: {
    type: 'barracks',
    kind: 'building',
    label: 'Oath Hall',
    description: 'Trains Oathbound and Ashen Arbalests for open-field control.',
    cost: 160,
    buildTime: 14,
    hp: 430,
    radius: 36,
    speed: 0,
    range: 0,
    damage: 0,
    attackCooldown: 0,
    sight: 260,
    armor: 'structure',
    bonusAgainst: [],
    bonusDamage: 0,
    terror: 10,
    ward: 16,
    supplyCost: 0,
    supplyProvided: 8,
  },
  turret: {
    type: 'turret',
    kind: 'building',
    label: 'Warding Pyre',
    description: 'Defensive flame shrine. Attacks enemies and stabilizes nearby resolve.',
    cost: 120,
    buildTime: 11,
    hp: 260,
    radius: 27,
    speed: 0,
    range: 172,
    damage: 13,
    attackCooldown: 0.82,
    sight: 270,
    armor: 'structure',
    bonusAgainst: ['light'],
    bonusDamage: 5,
    terror: 18,
    ward: 34,
    supplyCost: 0,
    supplyProvided: 0,
  },
}

export const RACE_DEFS: Record<RaceId, RaceDef> = {
  candlebound: {
    id: 'candlebound',
    name: 'Candlebound Remnant',
    shortName: 'Remnant',
    tagline: 'Balanced ward lines and reliable production.',
    style: 'Stabilize resolve, take safe expansions, and win with disciplined mixed armies.',
    color: 0xc4a85f,
    accent: 0xf3e6bf,
    unitScale: 1,
    incomeRate: 1,
    resolveDrift: 0,
    overrides: {},
  },
  hollow: {
    id: 'hollow',
    name: 'Hollow Choir',
    shortName: 'Choir',
    tagline: 'Cheap pressure, dread auras, and fragile swarms.',
    style: 'Flood lanes early, use terror to slow enemy armies, and avoid long static fights.',
    color: 0x95383d,
    accent: 0xd79a7a,
    unitScale: 0.92,
    incomeRate: 1.08,
    resolveDrift: -8,
    overrides: {
      worker: {
        label: 'Mute Thrall',
        description: 'Cheap servant that harvests quickly but barely resists dread.',
        cost: 36,
        buildTime: 4.8,
        hp: 34,
        speed: 108,
        sight: 178,
        terror: 3,
        ward: 0,
        supplyCost: 1,
      },
      vanguard: {
        label: 'Choir Husk',
        description: 'Low-cost shock infantry. Dangerous in numbers, poor alone.',
        cost: 54,
        buildTime: 6.5,
        hp: 56,
        speed: 106,
        damage: 9,
        attackCooldown: 0.82,
        terror: 12,
        ward: 0,
        supplyCost: 1,
      },
      skirmisher: {
        label: 'Bellwraith',
        description: 'Fast ranged harrier that projects dread into enemy lines.',
        cost: 82,
        buildTime: 8.4,
        hp: 44,
        speed: 136,
        range: 150,
        damage: 7,
        terror: 14,
        ward: 0,
        supplyCost: 2,
      },
      command: {
        label: 'Choir Spire',
        description: 'A resonant command shrine that feeds the Choir economy.',
        hp: 630,
        sight: 300,
        terror: 24,
        ward: 4,
      },
      barracks: {
        label: 'Vesper Pit',
        description: 'Breeds Choir Husks and Bellwraiths quickly.',
        cost: 138,
        buildTime: 11.5,
        hp: 350,
        terror: 18,
        ward: 2,
        supplyProvided: 10,
      },
      turret: {
        label: 'Tolling Stake',
        description: 'A brittle defensive stake that punishes light raiders.',
        cost: 105,
        buildTime: 9,
        hp: 205,
        damage: 11,
        attackCooldown: 0.62,
        terror: 22,
        ward: 0,
      },
    },
  },
  sepulcher: {
    id: 'sepulcher',
    name: 'Sepulcher Host',
    shortName: 'Host',
    tagline: 'Elite iron bodies, slow tempo, brutal durability.',
    style: 'Survive the opener, claim fewer but richer positions, and crush with expensive armored units.',
    color: 0x8fae72,
    accent: 0xd8e7b1,
    unitScale: 1.12,
    incomeRate: 0.94,
    resolveDrift: 6,
    overrides: {
      worker: {
        label: 'Reliquary Mason',
        description: 'Slow, durable worker used to build fortified positions.',
        cost: 55,
        buildTime: 7.2,
        hp: 58,
        speed: 82,
        ward: 8,
        supplyCost: 1,
      },
      vanguard: {
        label: 'Iron Penitent',
        description: 'Expensive armored infantry that anchors fights and breaks structures.',
        cost: 92,
        buildTime: 10.5,
        hp: 108,
        speed: 74,
        damage: 15,
        attackCooldown: 1.08,
        bonusDamage: 7,
        terror: 2,
        ward: 12,
        supplyCost: 3,
      },
      skirmisher: {
        label: 'Vault Arbalist',
        description: 'Deliberate ranged defender with high damage and poor reposition speed.',
        cost: 116,
        buildTime: 12,
        hp: 72,
        speed: 96,
        range: 154,
        damage: 11,
        attackCooldown: 0.9,
        ward: 7,
        supplyCost: 3,
      },
      command: {
        label: 'Sepulcher Gate',
        description: 'Heavy central bastion with a strong resolve aura.',
        hp: 860,
        sight: 335,
        terror: 6,
        ward: 58,
      },
      barracks: {
        label: 'Reliquary Foundry',
        description: 'Slow production hall for elite Host infantry.',
        cost: 190,
        buildTime: 17,
        hp: 560,
        ward: 28,
        supplyProvided: 6,
      },
      turret: {
        label: 'Grave Lantern',
        description: 'Costly defensive lantern with heavy shots and a strong ward.',
        cost: 145,
        buildTime: 13,
        hp: 340,
        damage: 17,
        attackCooldown: 1,
        ward: 46,
      },
    },
  },
}

export const RACE_POWER_DEFS: Record<
  RaceId,
  { label: string; description: string; cost: number; cooldown: number }
> = {
  candlebound: {
    label: 'Beacon Oath',
    description: 'Restore resolve and mend nearby wounds across the Remnant warband.',
    cost: 45,
    cooldown: 48,
  },
  hollow: {
    label: 'Open the Vesper Pit',
    description: 'Trade iron for an immediate Choir Husk at the command spire.',
    cost: 38,
    cooldown: 42,
  },
  sepulcher: {
    label: 'Seal the Vaults',
    description: 'Restore damaged structures and steady the Host behind its walls.',
    cost: 60,
    cooldown: 58,
  },
}

export function getEntityDef(type: EntityType, race: RaceId = 'candlebound'): EntityDef {
  const base = ENTITY_DEFS[type]
  const overrides = RACE_DEFS[race].overrides[type] ?? {}
  return { ...base, ...overrides, type, kind: base.kind }
}

export const BUILDABLES: BuildingType[] = ['barracks', 'turret']
export const TRAINABLE_BY_BUILDING: Record<BuildingType, UnitType[]> = {
  command: ['worker'],
  barracks: ['vanguard', 'skirmisher'],
  turret: [],
}

export const ORE_PER_TRIP = 10
export const HARVEST_SECONDS = 1.1
export const STARTING_ORE = 260
export const PASSIVE_AI_ORE_PER_SECOND = 3.2
export const RUIN_TIDE_PERIOD = 92
export const TERROR_RANGE = 250
export const WARD_RANGE = 230
