import type { BuildingType, EntityDef, EntityType, RaceDef, RaceId, UnitType } from './types'

export const ENTITY_DEFS: Record<UnitType | BuildingType, EntityDef> = {
  worker: {
    type: 'worker',
    kind: 'unit',
    label: 'Fieldwright',
    description: 'Harvests black iron and raises modular field structures for the Cinder Compact.',
    cost: 45,
    buildTime: 6,
    hp: 44,
    radius: 13,
    speed: 96,
    range: 26,
    damage: 3,
    attackCooldown: 1.1,
    sight: 190,
    armor: 'laborer',
    bonusAgainst: [],
    bonusDamage: 0,
    terror: 0,
    ward: 4,
    supplyCost: 1,
    supplyProvided: 0,
  },
  vanguard: {
    type: 'vanguard',
    kind: 'unit',
    label: 'Pikeguard',
    description: 'Disciplined line infantry whose shields and polearms anchor a mixed formation.',
    cost: 72,
    buildTime: 8,
    hp: 84,
    radius: 15,
    speed: 88,
    range: 28,
    damage: 10,
    attackCooldown: 0.9,
    sight: 230,
    armor: 'armored',
    bonusAgainst: ['structure'],
    bonusDamage: 4,
    terror: 4,
    ward: 8,
    supplyCost: 2,
    supplyProvided: 0,
  },
  skirmisher: {
    type: 'skirmisher',
    kind: 'unit',
    label: 'Cinder Arbalest',
    description: 'Mobile ranged support with strong armor-piercing volleys and a vulnerable firing line.',
    cost: 95,
    buildTime: 10,
    hp: 58,
    radius: 14,
    speed: 120,
    range: 148,
    damage: 9,
    attackCooldown: 0.82,
    sight: 260,
    armor: 'light',
    bonusAgainst: ['armored'],
    bonusDamage: 6,
    terror: 5,
    ward: 3,
    supplyCost: 2,
    supplyProvided: 0,
  },
  command: {
    type: 'command',
    kind: 'building',
    label: 'March Keep',
    description: 'Compact command stronghold, public kitchen, workshop, and anchor against the Dread Tide.',
    cost: 0,
    buildTime: 0,
    hp: 720,
    radius: 46,
    speed: 0,
    range: 0,
    damage: 0,
    attackCooldown: 0,
    sight: 320,
    armor: 'structure',
    bonusAgainst: [],
    bonusDamage: 0,
    terror: 12,
    ward: 40,
    supplyCost: 0,
    supplyProvided: 14,
  },
  barracks: {
    type: 'barracks',
    kind: 'building',
    label: 'Assembly Hall',
    description: 'Trains Pikeguards and Cinder Arbalests while extending the Compact supply network.',
    cost: 160,
    buildTime: 14,
    hp: 430,
    radius: 36,
    speed: 0,
    range: 0,
    damage: 0,
    attackCooldown: 0,
    sight: 260,
    armor: 'structure',
    bonusAgainst: [],
    bonusDamage: 0,
    terror: 10,
    ward: 16,
    supplyCost: 0,
    supplyProvided: 8,
  },
  turret: {
    type: 'turret',
    kind: 'building',
    label: 'Signal Bastion',
    description: 'A compact watchtower whose black-iron beacon attacks raiders and steadies nearby troops.',
    cost: 120,
    buildTime: 11,
    hp: 260,
    radius: 27,
    speed: 0,
    range: 172,
    damage: 13,
    attackCooldown: 0.82,
    sight: 270,
    armor: 'structure',
    bonusAgainst: ['light'],
    bonusDamage: 5,
    terror: 18,
    ward: 34,
    supplyCost: 0,
    supplyProvided: 0,
  },
}

export const RACE_DEFS: Record<RaceId, RaceDef> = {
  compact: {
    id: 'compact',
    name: 'Cinder Compact',
    shortName: 'Compact',
    tagline: 'Disciplined combined arms and adaptable fieldworks.',
    style: 'Protect supply lines, rotate formations, and make ordinary units stronger through coordination.',
    protagonist: 'Marshal Mara Veyr',
    ethos: 'No oath stands above the living.',
    cost: 'The Compact rejects sacrifice while surviving through conscription, triage, and erased graves.',
    silhouette: 'Grounded late-medieval armor, visible faces, square shields, polearms, and repaired field cloth.',
    color: 0x6f8fa5,
    accent: 0xf0c27b,
    unitScale: 1,
    incomeRate: 1,
    resolveDrift: 0,
    overrides: {},
  },
  ascendancy: {
    id: 'ascendancy',
    name: 'Gloam Ascendancy',
    shortName: 'Ascendancy',
    tagline: 'Few perfected bodies that create local inevitability.',
    style: 'Commit expensive Crowned units deliberately, spread terror, and force one decisive engagement.',
    protagonist: 'Aurel Sorn, the First Crowned',
    ethos: 'No one should need courage merely to endure life.',
    cost: 'Absolution ends fear and inherited rank by ending the private self that could choose otherwise.',
    silhouette: 'Processional cloth, porcelain veils, blackened gold, and asymmetrical bodies shaped by one purpose.',
    color: 0x8f3449,
    accent: 0xe4b18c,
    unitScale: 1.07,
    incomeRate: 1.04,
    resolveDrift: 6,
    overrides: {
      worker: {
        label: 'Votary',
        description: 'A swift untransformed adherent who gathers, scouts, and tends Ascendancy sanctuaries.',
        cost: 40,
        buildTime: 5.2,
        hp: 38,
        speed: 112,
        sight: 205,
        terror: 2,
        ward: 2,
        supplyCost: 1,
      },
      vanguard: {
        label: 'Crowned Bulwark',
        description: 'A transformed protector made brutally absolute: durable, terrifying, and costly to replace.',
        cost: 104,
        buildTime: 11.5,
        hp: 124,
        radius: 18,
        speed: 78,
        damage: 16,
        attackCooldown: 1.08,
        terror: 20,
        ward: 5,
        supplyCost: 3,
      },
      skirmisher: {
        label: 'Veil Seer',
        description: 'A deliberate ranged specialist that exposes armor and carries dread across a firing line.',
        cost: 112,
        buildTime: 11,
        hp: 62,
        speed: 106,
        range: 160,
        damage: 11,
        attackCooldown: 0.96,
        sight: 285,
        terror: 13,
        ward: 3,
        supplyCost: 3,
      },
      command: {
        label: 'House of Quiet',
        description: 'Hospice, court, and command sanctuary where Votaries hear the promise of Absolution.',
        hp: 760,
        sight: 330,
        terror: 30,
        ward: 10,
        supplyProvided: 13,
      },
      barracks: {
        label: 'Chrysalis Court',
        description: 'A formal transformation hall that prepares Crowned Bulwarks and Veil Seers.',
        cost: 182,
        buildTime: 16,
        hp: 470,
        terror: 22,
        ward: 8,
        supplyProvided: 8,
      },
      turret: {
        label: 'Witness Needle',
        description: 'A veiled watch-organ that marks fast intruders and radiates controlled dread.',
        cost: 135,
        buildTime: 12,
        hp: 275,
        range: 185,
        damage: 14,
        attackCooldown: 0.9,
        terror: 24,
        ward: 4,
      },
    },
  },
  concord: {
    id: 'concord',
    name: 'Elder Concord',
    shortName: 'Concord',
    tagline: 'Elven sight, dwarven craft, and giant battlefield weight.',
    style: 'Prepare terrain, share vision, and combine specialists whose weaknesses are covered by another people.',
    protagonist: 'Tavra Nine-Reeds',
    ethos: 'The living inherit a world, not ownership of it.',
    cost: 'The Concord protects memory while letting old age harden into authority over younger lives.',
    silhouette: 'Mineral-blue cords unify bark-lacquer elves, basalt-armored dwarves, and terraced giants.',
    color: 0x6f9c78,
    accent: 0xc7d89e,
    unitScale: 1.08,
    incomeRate: 0.96,
    resolveDrift: 10,
    overrides: {
      worker: {
        label: 'Dorrin Stonewright',
        description: 'A durable dwarven engineer who tunes foundations and raises negotiated fortifications.',
        cost: 55,
        buildTime: 7.2,
        hp: 58,
        speed: 82,
        sight: 210,
        ward: 10,
        supplyCost: 1,
      },
      vanguard: {
        label: 'Orrun Warden',
        description: 'A young giant who anchors a mixed host and breaks fortifications with measured force.',
        cost: 108,
        buildTime: 12.5,
        hp: 136,
        radius: 19,
        speed: 68,
        damage: 18,
        attackCooldown: 1.22,
        bonusDamage: 9,
        terror: 2,
        ward: 12,
        supplyCost: 4,
      },
      skirmisher: {
        label: 'Lethai Waybow',
        description: 'An elven path-reader with exceptional sight, range, and repositioning speed.',
        cost: 106,
        buildTime: 10.8,
        hp: 58,
        speed: 132,
        range: 172,
        damage: 9,
        attackCooldown: 0.78,
        sight: 315,
        ward: 6,
        supplyCost: 2,
      },
      command: {
        label: 'Meeting Stone',
        description: 'A shared hall grown through root tension, tuned stone, and a giant boundary marker.',
        hp: 900,
        sight: 360,
        terror: 4,
        ward: 62,
        supplyProvided: 13,
      },
      barracks: {
        label: 'Treaty Grove',
        description: 'A mixed-species muster ground that prepares Orrun Wardens and Lethai Waybows.',
        cost: 188,
        buildTime: 17,
        hp: 570,
        ward: 32,
        supplyProvided: 7,
      },
      turret: {
        label: 'Resonance Bell',
        description: 'A dwarven tuned-stone defense that strikes intruders and carries resolve through the ground.',
        cost: 150,
        buildTime: 13,
        hp: 340,
        range: 190,
        damage: 16,
        attackCooldown: 1,
        ward: 46,
      },
    },
  },
}

export const RACE_POWER_DEFS: Record<
  RaceId,
  { label: string; description: string; cost: number; cooldown: number }
> = {
  compact: {
    label: 'No One Left Uncounted',
    description: 'Restore resolve and mend every Compact unit through the field relief network.',
    cost: 45,
    cooldown: 48,
  },
  ascendancy: {
    label: 'Manifest Absolution',
    description: 'Spend black iron to manifest an immediate Crowned Bulwark at the House of Quiet.',
    cost: 72,
    cooldown: 56,
  },
  concord: {
    label: 'Wake the Ground',
    description: 'Restore living structures and carry stabilizing resonance through the mixed host.',
    cost: 60,
    cooldown: 58,
  },
}

export function getEntityDef(type: EntityType, race: RaceId = 'compact'): EntityDef {
  const base = ENTITY_DEFS[type]
  const overrides = RACE_DEFS[race].overrides[type] ?? {}
  return { ...base, ...overrides, type, kind: base.kind }
}

export const BUILDABLES: BuildingType[] = ['barracks', 'turret']
export const TRAINABLE_BY_BUILDING: Record<BuildingType, UnitType[]> = {
  command: ['worker'],
  barracks: ['vanguard', 'skirmisher'],
  turret: [],
}

export const ORE_PER_TRIP = 10
export const HARVEST_SECONDS = 1.1
export const STARTING_ORE = 260
export const PASSIVE_AI_ORE_PER_SECOND = 0
export const RUIN_TIDE_PERIOD = 92
export const TERROR_RANGE = 250
export const WARD_RANGE = 230
